# Generated by Django 2.0.5 on 2018-08-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '计数', 'verbose_name_plural': '文章计数'},
        ),
    ]
