# Generated by Django 2.0.5 on 2018-07-29 04:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('changedate', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章管理',
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtype', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='blogtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.BlogType'),
        ),
    ]
