# Generated by Django 2.0.5 on 2018-07-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180729_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='changedate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blogtype',
            name='blogtype',
            field=models.CharField(max_length=10, verbose_name='类别'),
        ),
    ]
