# Generated by Django 2.0.5 on 2018-07-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180729_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-changedate'], 'verbose_name': '文章', 'verbose_name_plural': '文章管理'},
        ),
    ]
