# Generated by Django 2.0.5 on 2018-07-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180730_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtype',
            old_name='blogtype',
            new_name='blog_type',
        ),
    ]
