# Generated by Django 2.0.5 on 2018-08-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20180801_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
